# Generated by Django 5.0.6 on 2024-06-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stock', models.IntegerField(default=100)),
                ('price', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static/blog')),
                ('season', models.CharField(choices=[('winter', 'W'), ('summer', 'S'), ('monsoon', 'M')], max_length=100)),
                ('gender', models.CharField(choices=[('male', 'M'), ('female', 'F')], max_length=100)),
                ('discount', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory')),
            ],
        ),
    ]
