# Generated by Django 5.0.6 on 2024-06-16 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
