# Generated by Django 5.0.6 on 2024-06-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('38', '38'), ('39', '39'), ('40', '40')], max_length=100),
        ),
    ]
